package pizzeria.internal.menu;

public enum Topping {
    TOMATO_SAUCE, MOZZARELLA_CHEESE, BASIL, TOMATO_SLICES, PEPPERONI, SAUSAGE, GROUND_BEEF,
    BACON_BITS, SPINACH, MUSHROOMS, CARAMELIZED_ONIONS, GREEN_PEPPERS, OLIVES, PINEAPPLES, SLICED_HAM
}
